# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./docker/app/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: newapple4g/text_metrics_app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '3001:3001'
            - '3002:3002'
            - '3003:3003'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            PHP_IDE_CONFIG: serverName=Docker
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - ruts
#            - languagetool
        container_name: 'text_metrics_app'
    pgsql:
        image: 'postgres:latest'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
            - './docker/pgsql/entrypoint.d:/docker-entrypoint-initdb.d'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
        container_name: 'text_metrics_pgsql'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        container_name: 'text_metrics_redis'
    ruts:
        image: 'newapple4g/ruts'
        build:
            context: ./modules/ruTS
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8009:8009'
        volumes:
            - './modules/ruTS/app:/code/app'
        networks:
            - sail
        container_name: 'text_metrics_ruts'
#    languagetool:
#        image: erikvl87/languagetool
#        container_name: 'text_metrics_languagetool'
#        ports:
#            - 8010:8010  # Using default port from the image
#        networks:
#            - sail
#        environment:
##            - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
#            - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
#            - Java_Xmx=1g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
##        volumes:
##            - /path/to/ngrams/data:/ngrams
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
